# Generated by Django 4.2.9 on 2024-01-29 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('askedAMotivationalQuote', models.BooleanField(default=False)),
                ('askedAboutDailyGoals', models.BooleanField(default=False)),
                ('askedAboutSkillorBook', models.BooleanField(default=False)),
                ('askedAboutFeelAtthisPoint', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
