# Generated by Django 4.2.9 on 2024-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addictbuddy', '0002_remove_accomplishments_askedamotivationalquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishments',
            name='askedAMotivationalQuote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accomplishments',
            name='askedAboutSkillorBook',
            field=models.BooleanField(default=False),
        ),
    ]
