# Generated by Django 4.2.9 on 2024-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addictbuddy', '0003_accomplishments_askedamotivationalquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishments',
            name='previousExchange',
            field=models.TextField(default=''),
        ),
    ]
