# Generated by Django 4.2.9 on 2024-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addictbuddy', '0004_accomplishments_previousexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishments',
            name='previousExchange2',
            field=models.TextField(default=''),
        ),
    ]
