# Generated by Django 5.0.1 on 2024-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='didChatWithBotToday',
            field=models.BooleanField(default=False),
        ),
    ]
