# Generated by Django 5.0.1 on 2024-01-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_days_user_didchatwithbottoday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='days',
            new_name='streak',
        ),
    ]
